name: Trest CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.2
      - name: Setup Kotlin
        uses: fwilhe2/setup-kotlin@0.2.0
      - name: Setup Java
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'oracle'
          java-version: 17
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run Unit Tests
        run: ./gradlew test
      - name: Upload APK
        uses: actions/upload-artifact@v4.3.1
        with: 
          name: app
          path: app/build/outputs/apk/py311/debug/app-py311-debug.apk
